name: Pre-commit Checks

on:
  pull_request:
    branches: [ master ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/pre-commit-check.yml'
      - '.openhands/pre-commit.sh'
  workflow_dispatch:  # Allow manual triggering

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper git operations
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    
    - name: Setup git
      run: |
        git config --global user.email "test@example.com"
        git config --global user.name "Test User"
    
    - name: Run black (format check)
      run: |
        python -m black --check src/ tests/
    
    - name: Run isort (import sorting check)
      run: |
        python -m isort --check-only src/ tests/
    
    - name: Run flake8 (linting)
      run: |
        python -m flake8 src/ tests/
    
    - name: Run mypy (type checking)
      run: |
        python -m mypy src/ tests/
    
    - name: Run pylint (comprehensive linting)
      run: |
        python -m pylint src/ tests/